c("A colleague who hates Christmas",
  "A colleague who got drunk in Georgia",
  "A colleague who has more than 1 pet",
  "A colleague who is a member of todays party team",
  "A colleague who is colleague for less than 6 months",
  "A colleague who is part of team Connika",
  "A colleague who has not had Corona",
  "A colleague who has grandchildren",
  "A colleague who arranged a Pump Track in Noorderpark",
  "A colleague who has published a book",
  "A colleague who has lived outside of the Netherlands",
  "A colleague who decorates the Christmas tree half November",
  "A colleague who is left handed",
  "A colleague who is a professional singer",
  "A colleague who as been on television",
  "A colleague who doesn't wear sneakers today",
  "A colleague who you've never talked to before",
  "A colleague who is a vegetarian or vegan",
  "A colleague who is a morning person",
  "A colleague who has a larger shoe size than you",
  "A colleague who dislikes cilantro",
  "A colleague who is a volunteer",
  "A colleague who is afraid of heights",
  "A colleague who lives in Houten",
  "A colleague who ran (half) a marathon",
  "A colleague who recently got married",
  "A colleague who wears a striped shirt",
  "A colleague who knits their own sweaters",
  "A colleague who is member of the Dienstraad",
  "A colleague who plays a musical instrument",
  "A colleague who is Suske and Wiske fan/expert",
  "A colleague who is cycling fan/fanatic",
  "A colleague who has a tattoo",
  "A colleague who is learning a foreign language",
  "A colleague who can drink coffee at night and still fall asleep",
  "A colleague who bikes to work",
  "A colleague who met their partner at the UU",
  "A colleague who went on holiday by train this summer",
  "A colleague who used to work at the Humanities factulty",
  "A colleague who practices martial arts",
  "A colleague who has joined a demonstration",
  "A colleague who is going to play \"sjoelen\" with you",
  "A colleague who is subscribed to a newspaper",
  "A colleague who ate pasta last night",
  "A colleague who has no TV",
  "A colleague who has their birthday in October",
  "A colleague who knows CPR",
  "A colleague who sings in the shower",
  "A colleague who has gone on a safari",
  "A colleague who lives in the province of Gelderland"
)
