c(
  "Een collega die Kerst haat",
  "Een collega die dronken werd in Georgie",
  "Een collega die meer dan een huisdier heeft",
  "Een collega die in de feestcommissie zit",
  "Een collega die korter dan 6 maanden in dienst is",
  "Een collega die onderdeel is van team Connika",
  "Een collega die nog geen corona gehad heeft",
  "Een collega die kleinkind(eren) heeft",
  "Een collega die een Pump Track in het Noorderpark geregeld heeft",
  "Een collega die een boek gepubliceerd heeft",
  "Een collega die buiten Nederland heeft gewoond",
  "Een collega die half november de kerstboom opzet",
  "Een collega die linkshandig is",
  "Een collega die een professionele zanger is",
  "Een collega die op TV geweest is",
  "Een collega die vandaag geen sneakers draagt",
  "Een collega die met wie je nooit eerder hebt gesproken",
  "Een collega die vegetarier of veganist is",
  "Een collega die een ochtendmens is",
  "Een collega die een grotere schoenmaat heeft dan jij",
  "Een collega die niet van (verse) koriander houdt",
  "Een collega die vrijwilligerswerk doet",
  "Een collega die hoogtevrees heeft",
  "Een collega die in Houten woont",
  "Een collega die een hele/halve marathon heeft gelopen",
  "Een collega die meer dan drie kinderen heeft",
  "Een collega die pas getrouwd is",
  "Een collega die een gestreept shirt aan heeft",
  "Een collega die zelf truien breit",
  "Een collega die in de dienstraad zit",
  "Een collega die een muziekinstrument speelt",
  "Een collega die een Suske en Wiske fan/expert is",
  "Een collega die een wielrenfan is",
  "Een collega die een tatoeage heeft",
  "Een collega die een vreemde taal aan het leren is",
  "koffie kan drinken 's avonds en nog steeds kan slapen",
  "Een collega die naar werk fietst",
  "Een collega die hun partner bij de UU ontmoet heeft",
  "Een collega die met de trein op vakantie ging afgelopen zomer",
  "Een collega die voorheen bij de faculteit GW werkte",
  "Een collega die een vechtsport doet",
  "Een collega die aan een demonstratie heeft meegedaan",
  "Een collega die met wie je gaat sjoelen",
  "Een collega die geabonneerd is op een krant",
  "Een collega die gisterenavond pasta heeft gegeten",
  "Een collega die geen TV heeft",
  "Een collega die jarig is in oktober",
  "Een collega die kan reanimeren",
  "Een collega die zingt onder de douche",
  "Een collega die op safari is geweest",
  "Een collega die in Gelderland woont"
  )
