c(
  "Kerst haat",
  "pas getrouwd is",
  "dronken werd in Georgië",
  "een gestreept shirt aan heeft",
  "meer dan één huisdier heeft",
  "zelf truien breit",
  "in de feestcommissie zit",
  "in de dienstraad zit",
  "korter dan 6 maanden in dienst is",
  "een muziekinstrument speelt",
  "onderdeel is van team Connika",
  "een Suske en Wiske fan/expert is",
  "nog geen corona gehad heeft",
  "een wielrenfan is",
  "kleinkind(eren) heeft",
  "een tatoeage heeft",
  "een Pump Track in het Noorderpark geregeld heeft",
  "een vreemde taal aan het leren is",
  "een boek gepubliceerd heeft",
  "koffie kan drinken 's avonds en nog steeds kan slapen",
  "buiten Nederland heeft gewoond",
  "naar werk fietst",
  "half november de kerstboom opzet",
  "hun partner bij de UU ontmoet heeft",
  "linkshandig is",
  "met de trein op vakantie ging afgelopen zomer",
  "een professionele zanger is",
  "voorheen bij de faculteit GW werkte",
  "op TV geweest is",
  "een vechtsport doet",
  "vandaag geen sneakers draagt",
  "aan een demonstratie heeft meegedaan",
  "met wie je nooit eerder hebt gesproken",
  "met wie je gaat sjoelen",
  "vegetariër of veganist is",
  "geabonneerd is op een krant",
  "een ochtendmens is",
  "gisterenavond pasta heeft gegeten",
  "een grotere schoenmaat heeft dan jij",
  "geen TV heeft",
  "niet van (verse) koriander houdt",
  "jarig is in oktober",
  "vrijwilligerswerk doet",
  "kan reanimeren",
  "hoogtevrees heeft",
  "zingt onder de douche",
  "in Houten woont",
  "op safari is geweest",
  "een hele/halve marathon heeft gelopen",
  "in Gelderland woont",
  "meer dan drie kinderen heeft"
  )
