c(
  "hates Christmas",
  "recently got married",
  "got drunk in Georgia",
  "wears a striped shirt",
  "has more than 1 pet",
  "knits their own sweaters",
  "is a member of todays party team",
  "is member of the Dienstraad",
  "is colleague for less than 6 months",
  "plays a musical instrument",
  "is part of team Connika",
  "is Suske and Wiske fan/expert",
  "has not had Corona",
  "is cycling fan/fanatic",
  "has grandchildren",
  "has a tattoo",
  "arranged a Pump Track in Noorderpark",
  "is learning a foreign language",
  "has published a book",
  "can drink coffee at night and still fall asleep",
  "has lived outside of the Netherlands",
  "bikes to work",
  "decorates the Christmas tree half November",
  "met their partner at the UU",
  "is left handed",
  "went on holiday by train this summer",
  "is a professional singer",
  "used to work at the Humanities faculty",
  "as been on television",
  "practices martial arts",
  "doesn't wear sneakers today",
  "has joined a demonstration",
  "you've never talked to before",
  "is going to play \"sjoelen\" with you",
  "is a vegetarian or vegan",
  "is subscribed to a newspaper",
  "is a morning person",
  "ate pasta last night",
  "has a larger shoe size than you",
  "has no TV",
  "dislikes cilantro",
  "has their birthday in October",
  "is a volunteer",
  "knows CPR",
  "is afraid of heights",
  "sings in the shower",
  "lives in Houten",
  "has gone on a safari",
  "ran (half) a marathon",
  "lives in the province of Gelderland",
  "has more than three children"
  )
